n1 = str(input("Digite uma tarefa: "))
n2 = str(input("digite a segunda tarefa: "))
n3 = str(input("digite a terceira tarefa: "))
n4 = str(input("digite a quarta tarefa: "))
n5 = str(input("digite a quinta tarefa: "))
n6 = str(input("digite a sexta tarefa: "))
n7 = str(input("digite a setima tarefa: "))
n8 = str(input("digite a oitava tarefa: "))
n9 = str(input("digite a nona tarefa: "))
n10 = str(input("digite a decima tarefa: "))

print('a primeira tarefa é: ', n1)
print('a segunda tarefa é: ', n2)
print('a terceira tarefa é: ', n3)
print('a quarta tarefa é: ', n4)
print('a quinta tarefa é: ', n5)
print('a sexta tarefa é: ', n6)
print('a setima tarefa é: ', n7)
print('a oitava tarefa é: ', n8)
print('a nona tarefa é: ', n9)
print('a decima tarefa é: ', n10)
